### ISSUE TITLE
相互リンク依頼が来た。

### ISSUE THREAD

**Issue by nna774** [kmc-jp/2015AprilFool#138]
https://inside.kmc.gr.jp/m2w/combat/62

**Comment by t-uda** [comment]
やります．そういえば CAMPHOR- のやつもリンク集に載せてないという致命的なアレがアレなのでついでにソレします．

**Comment by nna774** [comment]
おおおありがとうございますお願いします。

**Comment by t-uda** [comment]
![](http://nojima.kmc.jp/imagia/4cafb677da11c29393bec34a18b80049667efac6.png)
![](http://nojima.kmc.jp/imagia/ea5c99c69625939c23acc0830686e38fd55fa9f9.png)

後ろの奴の点滅してる存在感な
