### ISSUE TITLE
「岡本暁広〄精神と時の髪」の〄がEUC-JPで表現できない

### ISSUE THREAD

**Issue by 1995hnagamin** [kmc-jp/2015AprilFool#143]
岡本暁広〄精神と時の髪(@henkma)様が8191番をゲットしましたが、
〄がEUC-JPで表現できないためキリ番ゲッター様のリストに追加できません＞＜

https://twitter.com/henkma/status/583070276318965760

**Comment by primenumber** [comment]
,r"´Ｊヽ
　 　 l 　 | 　 l
　　　ゝＳ　.ノ

**Comment by 1995hnagamin** [comment]
LGTM

**Comment by 1995hnagamin** [comment]
<img src="path/to/jis.gif" alt="jis"></img>

**Comment by nna774** [comment]
良さ

**Comment by 1995hnagamin** [comment]
`<option>`中に`<img>`タグ入れてんだからyosinani表示してよ💢💢💢💢💢💢💢💢

**Comment by nna774** [comment]
あーそっかあれ option の中か。。。

2015-04-01 18:49 GMT+09:00 Hideaki Nagamine <notifications@github.com>:

**Comment by 1995hnagamin** [comment]
Webフォントで何とかならないか
http://tech.nitoyon.com/ja/blog/2012/04/23/why-uncopyable/

**Comment by 1995hnagamin** [comment]
誰か助けてくれ〜〜〜〜〜〜
https://github.com/kmc-jp/2015AprilFool/commit/af91358f23db88c8fc52e9e6373fe812abcb66f9

**Comment by 1995hnagamin** [comment]
まあいいか
