### ISSUE TITLE
㊗️ 20000アクセス突破 打ち上げ

### ISSUE THREAD

**Issue by pastak** [kmc-jp/2015AprilFool#147]
:confetti_ball: めでたいから関係各位で打ち上げ行くぞ！！！！！！！！！！！！

## 案

[![Gyazo](http://i.gyazo.com/304772296be5a7b1f9931618ee64a1f2.jpg)](https://vine.co/v/OMxJlWXEq6v)

via [https://vine.co/v/OMxJlWXEq6v](https://vine.co/v/OMxJlWXEq6v)

- 場所: [焼肉・塩ホルモン アジェ®松原本店](http://maps.google.co.jp/maps/ms?hl=ja&ie=UTF8&msa=0&msid=108064853931276303203.0004650fa0bfdcbcc064a&ll=35.001193,135.768925&spn=0.006433,0.008304&z=17)
- 食物: 焼肉、**ホソ！！！！！！！！！！！！！！！！！！！！！！！！！**
  - 青！！！！！
   - ![](https://pbs.twimg.com/media/BYY2BY_CQAAnK6c.jpg:large)
  - チカラコブも旨いぞ
- 予算: １人4000〜5000円くらい（経験則

他に案があれば書いて下さい。

参加希望者は参加の旨と大体の希望日をください！

**Comment by nonylene** [comment]
金曜日か土曜日か日曜日がよさそう！！

**Comment by t-uda** [comment]
ホルモン苦手なんですが普通の肉も食えますか．

**Comment by pastak** [comment]
普通の肉もあります！！！

**Comment by t-uda** [comment]
よっしゃ！！！！！11(土)と12(土)ならいけます！！！！！！！！！！！！！！！！

**Comment by t-uda** [comment]
もしかして土日って明日明後日か．そっちもいけます！！！！

金曜はムリごめん

**Comment by pastak** [comment]
11か12なるほど！

とりあえずその辺狙いにしましょう

**Comment by t-uda** [comment]
まぁそもそも明日明後日は急過ぎて予約とれねんじゃねっていうアレがある．来週も同じかもしれんが．

**Comment by tyage** [comment]
12日、TOEICがある...

**Comment by tyage** [comment]
11ならいけます

**Comment by nonylene** [comment]
11行けそうです

**Comment by pastak** [comment]
僕も11日行けそうです

**Comment by nna774** [comment]
11++

**Comment by pastak** [comment]
@primenumber @hatsusato @1995hnagamin 皆さんもいかがでしょう。

（https://github.com/kmc-jp/2015AprilFool/graphs/contributors を見た）

**Comment by primenumber** [comment]
良さ 11++

**Comment by 1995hnagamin** [comment]
4/11いいと思います

**Comment by pastak** [comment]
11日にするかぁ

**Comment by t-uda** [comment]
え，まだ予約してなかったん…… 大丈夫？

**Comment by hatsusato** [comment]
あっはいごはんたべたいです。予定は空けます。

**Comment by pastak** [comment]
@hatsusato @t-uda @nonylene @nna774 @primenumber @tyage @1995hnagamin 

アジェ松原本店予約しました。

開店時の入店しか予約できなかったので少し早いですが、**17時** にアジェ松原本店です。

よろしくおねがいします！！！！！！！

**Comment by pastak** [comment]
アジェ松原本店、駐輪場がないのでお気をつけください。部室からだと京阪四条 or 五条から歩くと良さそうです

**Comment by tyage** [comment]
![16487520353_2776e88290_k](https://cloud.githubusercontent.com/assets/177858/7101305/d2759cda-e08d-11e4-990d-9a7705331734.jpg)
